import { useState } from "react";
import { motion } from "motion/react";
import { ArrowDown, ArrowRight, Check, ExternalLink } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { BuildDemo } from "@/components/build-demo";
import { PageSection, SectionHeading } from "@/components/aca-layout";
import { BUY_URL, faq, flow, X_URL } from "@/lib/site";

const steps=[
  ["DESCRIBE","Tell ACA what you want to build.","AWAITING NATURAL LANGUAGE INPUT..."],
  ["UNDERSTAND","The agent interprets the intent.","INTENT GRAPH ASSEMBLED."],
  ["GENERATE","Code and contract architecture are created.","ARCHITECTURE AND CODE PATHS READY."],
  ["TEST","The generated system is tested.","RUNNING SIMULATED VALIDATION SUITE..."],
  ["DEPLOY","The application moves toward onchain deployment.","DEPLOYMENT PACKAGE PREPARED."],
  ["EXECUTE","The result becomes executable infrastructure.","READY FOR ONCHAIN EXECUTION."],
] as const;

export function AboutSection(){return <PageSection><SectionHeading label="01 / Concept" title="What is ACA?" copy="ARC CODING AGENT explores a new developer interface for the onchain era. Instead of beginning with thousands of lines of code, builders begin with intent."/><div className="grid gap-12 lg:grid-cols-[1fr_1.2fr]"><div className="space-y-5 leading-7 text-muted-foreground"><p>A prompt becomes architecture. Architecture becomes code. Code becomes contracts. Contracts become applications. Applications become economic actors.</p><p>ACA represents the idea of moving development closer to natural language while keeping execution onchain.</p></div><div className="hud-panel grid grid-cols-[1fr_auto] gap-x-4 p-5 sm:grid-cols-7 sm:items-center">{flow.map((item,i)=><div key={item} className="contents"><div className={`my-1 border px-3 py-3 text-center font-mono text-[10px] ${item==="ACA"?"border-primary bg-primary/15 text-primary-bright":"border-border text-ice"}`}>{item}</div>{i<flow.length-1&&<ArrowDown className="mx-auto size-4 text-primary sm:hidden"/>}{i<flow.length-1&&<ArrowRight className="mx-auto hidden size-4 text-primary sm:block"/>}</div>)}</div></div></PageSection>}

export function AgentSection(){const items=[["INTENT","UNDERSTAND WHAT YOU WANT TO BUILD"],["CODE","TRANSLATE INTENT INTO SOFTWARE"],["CONTRACT","GENERATE ONCHAIN LOGIC"],["TEST","VERIFY THE BUILD"],["DEPLOY","MOVE THE APPLICATION ONCHAIN"],["EXECUTE","LET THE NETWORK RUN IT"]];return <PageSection className="border-y border-border bg-background/65"><div className="grid items-center gap-12 lg:grid-cols-[.9fr_1.1fr]"><div className="relative mx-auto max-w-xl"><div className="absolute inset-10 rounded-full bg-primary/20 blur-3xl"/><img src="/assets/aca-logo.png" alt="ACA anime coding agent" loading="lazy" className="relative w-full object-contain drop-shadow-[0_0_45px_var(--primary)]"/></div><div><SectionHeading label="02 / Agent" title="Meet ACA" copy="THE ONCHAIN CODING AGENT"/><div className="grid gap-px bg-border sm:grid-cols-2">{items.map(([name,copy],i)=><motion.div key={name} whileHover={{x:4}} className="bg-background p-5"><span className="font-mono text-[10px] text-primary-bright">0{i+1}</span><h3 className="mt-2 font-display text-2xl font-bold">{name}</h3><p className="mt-1 font-mono text-[10px] text-muted-foreground">{copy}</p></motion.div>)}</div></div></div></PageSection>}

export function HowItWorks(){const [active,setActive]=useState(0);return <PageSection><div id="how-it-works" className="scroll-mt-24"><SectionHeading label="03 / Process" title="How it works" copy="Select a stage to inspect the agent's simulated system response."/><div className="grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><div className="grid gap-2">{steps.map(([title,copy],i)=><button key={title} onClick={()=>setActive(i)} className={`grid min-h-20 grid-cols-[auto_minmax(0,1fr)] items-center gap-5 border p-4 text-left transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${active===i?"border-primary bg-primary/10":"border-border bg-background/65 hover:border-primary/50"}`}><span className="font-mono text-xs text-primary-bright">0{i+1}</span><span><strong className="block font-display text-xl">{title}</strong><small className="text-muted-foreground">{copy}</small></span></button>)}</div><div className="hud-panel sticky top-24 h-fit p-6 font-mono text-xs"><p className="text-muted-foreground">ACA://PROCESS/0{active+1}</p><p className="mt-8 text-ice">&gt; {steps[active]?.[0].toLowerCase()}</p><p className="mt-4 text-primary-bright">{steps[active]?.[2]}</p><div className="mt-8 space-y-2">{["INTENT ENGINE","CODE ENGINE","CONTRACT ENGINE"].map(x=><p key={x} className="flex justify-between border-b border-border py-2"><span>{x}</span><Check className="size-4 text-primary-bright"/></p>)}</div></div></div></div></PageSection>}

export function BuildSection(){return <PageSection className="border-y border-border bg-background/65"><SectionHeading label="04 / Simulation" title="Build with intent" copy="Describe an idea and watch the conceptual pipeline assemble it into a simulated build."/><BuildDemo/></PageSection>}

export function ArcSection(){return <PageSection><SectionHeading label="05 / Environment" title="Why Arc?" copy="Arc is positioned as an economic infrastructure layer for internet-native activity. ACA's narrative is inspired by the emergence of onchain coding agents and the broader idea of AI agents participating in an onchain economy."/><div className="grid gap-4 md:grid-cols-5">{["AI AGENT","APPLICATION","SMART CONTRACT","USDC","ONCHAIN EXECUTION"].map((x,i)=><div key={x} className="relative border border-border bg-background/70 p-5 text-center font-mono text-xs text-ice">{x}{i<4&&<ArrowRight className="absolute -right-3 top-1/2 z-10 hidden size-5 -translate-y-1/2 text-primary md:block"/>}</div>)}</div><p className="mt-7 border-l-2 border-primary pl-4 text-sm text-muted-foreground">Independent community project inspired by Arc's public Onchain Coding Agent concept. No official affiliation or endorsement is claimed.</p></PageSection>}

export function RoadmapSection(){const phases=[["01","INITIALIZE","Brand · Website · Community · Lore · Launch","Concept"],["02","BUILD","Agent interface · Interactive terminal · Developer experiments · Community tools","Exploration"],["03","EXPAND","Onchain experiments · Agent integrations · Developer ecosystem","Planned"],["04","AUTONOMOUS","Future agent-powered infrastructure","Exploration"]];return <PageSection className="border-y border-border bg-background/65"><SectionHeading label="06 / Roadmap" title="System evolution"/><div className="grid gap-px bg-border md:grid-cols-4">{phases.map(([n,title,copy,status])=><div key={n} className="bg-background p-6"><span className="font-mono text-xs text-primary-bright">PHASE {n}</span><h3 className="mt-10 font-display text-3xl font-bold">{title}</h3><p className="mt-4 text-sm leading-6 text-muted-foreground">{copy}</p><span className="mt-8 inline-block border border-border px-2 py-1 font-mono text-[9px] uppercase text-ice">{status}</span></div>)}</div></PageSection>}

export function FAQSection(){return <PageSection><SectionHeading label="07 / FAQ" title="System queries"/><Accordion type="single" collapsible className="max-w-4xl">{faq.map(([q,a],i)=><AccordionItem key={q} value={`q-${i}`}><AccordionTrigger className="text-left font-display text-lg uppercase hover:no-underline">{q}</AccordionTrigger><AccordionContent className="max-w-3xl leading-7 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></PageSection>}

export function FinalCTA(){return <section className="relative overflow-hidden border-t border-border px-4 py-24 text-center sm:px-6 sm:py-36"><img src="/assets/aca-banner.jpeg" alt="" loading="lazy" className="absolute inset-0 size-full object-cover opacity-20"/><div className="absolute inset-0 bg-background/75"/><div className="relative mx-auto max-w-4xl"><p className="font-mono text-xs text-primary-bright">ACA://READY</p><p className="mt-6 font-display text-2xl uppercase text-ice">The next interface starts with an idea.</p><h2 className="mt-4 font-display text-5xl font-bold uppercase leading-[.9] text-glow sm:text-7xl">From prompt<br/>to onchain.</h2><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Button asChild><a href="/terminal">Enter Terminal</a></Button><Button asChild variant="outline"><a href={BUY_URL} target="_blank" rel="noopener noreferrer">Buy $ACA <ExternalLink/></a></Button>{X_URL?<Button asChild variant="outline"><a href={X_URL} target="_blank" rel="noopener noreferrer">Follow on X</a></Button>:<Button variant="outline" disabled>Follow on X · Soon</Button>}</div></div></section>}